baseURL = 'http://justcopy.net/'
languageCode = 'en-us'
title = 'Just copy'
theme = 'PaperMod'
googleAnalytics = 'G-YP2QQMZHDC'
enableRobotsTXT = true
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
env = 'production'

[params]
mainSections = ['posts']
ShareButtons = true
ShowShareButtons = true

[params.homeInfoParams]
Title = 'Hi! My name is Anton.'
Content = """I’ve made some difficult projects as an ux/ui designer.\n
My dream is make a product, that helps people to reach their goals, and make them happier.\n
Get in touch with me to use my skills and make your product better."""

[[params.socialIcons]]
name = "linkedin"
title = "LinkedIn"
url = "https://www.linkedin.com/in/acopylove/"
[[params.socialIcons]]
name = "telegram"
title = "Telegram"
url = "http://t.me/acopylove"
[[params.socialIcons]]
name = "email"
title = "Email"
url = "mailto:acopylove@gmail.com"

[languages]
  [languages.ru]
    contentDir = 'content/ru'
    languageCode = 'ru-RU'
    languageDirection = 'ltr'
    languageName = 'Русский'
    title = 'Justcopy'
    weight = 1
    [languages.ru.menu]
[[languages.ru.menu.main]]
      name = 'Посты'
      url = '/ru/posts'
      weight = 10
[[languages.ru.menu.main]]
      name = 'Портфолио'
      url = '/ru/folio'
      weight = 20

  [languages.en]
    contentDir = 'content/en/'
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'Justcopy'
    weight = 2
    [languages.en.menu]
[[languages.en.menu.main]]
      name = 'Posts'
      url = '/en/posts'
      weight = 10
[[languages.en.menu.main]]
      name = 'Porfolio'
      url = '/en/folio'
      weight = 20
